project_id = "vxxgvdlqvvchtlmqnrqf"

[functions.nylas-callback]
verify_jwt = false

[functions.nav-query-outbound-invoices]
verify_jwt = true

[functions.trigger-invoice-processing]
verify_jwt = true

[functions.trigger-bank-statement-processing]
verify_jwt = true

[functions.nav-token]
verify_jwt = true

[functions.nav-sync]
verify_jwt = true

[functions.save-credentials]
verify_jwt = true

[functions.query-nav-invoices]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.nylas-auth]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true