export const MODULE_LABELS: Record<string, string> = {
  // eaisyBill
  dashboard: 'Irányítópult',
  categories: 'Kategóriák',
  projects: 'Projektek',
  partners: 'Partnertörzs',
  invoices: 'Számlák',
  receivables: 'Kintlévőség',
  transactions: 'Tranzakciók',
  petty_cash: 'Házipénztár',
  general_ledger: 'Főkönyv',
  profit_loss: 'Eredménykimutatás',
  balance_sheet: 'Mérleg',
  annual_report: 'Beszámoló',
  vat_return: 'ÁFA Bevallás',
  salaries: 'Bérek/járulékok',
  working_time: 'Munkaidő',
  fixed_assets: 'TENY',
  integrations: 'Integrációk',
  exchange_rates: 'Árfolyamok',
  upload: 'Feltöltés',
  tickets: 'Hibajegyek',
  settings: 'Beállítások',
  shipments: 'Fuvarok',
  shipment_import: 'Excel Import',
  shipment_matching: 'Matching',
  // eaisyBooks
  portfolio: 'Portfólió',
  missing_invoices: 'Hiányzó számlák',
  tax_calendar: 'Adó naptár',
  reports: 'Riportok',
  approval_queue: 'Jóváhagyó rendszer',
  alerts: 'Riasztások',
  nav_deadlines: 'NAV határidők',
  payroll: 'Bérszámfejtés',
  onboarding: 'Onboarding',
  tao: 'TAO / KIVA',
  admin_audit: 'Audit napló',
  admin_gdpr: 'GDPR',
  admin_templates: 'Sablonok',
  admin_job_codes: 'Jogviszonykódok',
  admin_tax_params: 'Adómértékek',
  admin_legal: 'Jogszabály-frissítések',
  admin_office: 'Irodai beállítások',
  admin_permissions: 'Jogosultságkezelő',
  admin_accountants: 'Könyvelők kezelése',
  ai_assistant: 'AI Asszisztens',
  help: 'Segítség',
  profile: 'Profil',
};

export const PLATFORM_MODULE_GROUPS: Record<string, Record<string, { label: string; group: string }>> = {
  eaisybill: {
    dashboard: { label: 'Irányítópult', group: 'Áttekintés' },
    categories: { label: 'Kategóriák', group: 'Áttekintés' },
    projects: { label: 'Projektek', group: 'Áttekintés' },
    partners: { label: 'Partnertörzs', group: 'Áttekintés' },
    invoices: { label: 'Számlák', group: 'Pénzügyek' },
    receivables: { label: 'Kintlévőség', group: 'Pénzügyek' },
    transactions: { label: 'Tranzakciók', group: 'Pénzügyek' },
    petty_cash: { label: 'Házipénztár', group: 'Pénzügyek' },
    general_ledger: { label: 'Főkönyv', group: 'Könyvelés' },
    profit_loss: { label: 'Eredménykimutatás', group: 'Könyvelés' },
    balance_sheet: { label: 'Mérleg', group: 'Könyvelés' },
    annual_report: { label: 'Beszámoló', group: 'Könyvelés' },
    vat_return: { label: 'ÁFA Bevallás', group: 'Könyvelés' },
    salaries: { label: 'Bérek/járulékok', group: 'HR & Eszközök' },
    working_time: { label: 'Munkaidő', group: 'HR & Eszközök' },
    fixed_assets: { label: 'TENY', group: 'HR & Eszközök' },
    exchange_rates: { label: 'Árfolyamok', group: 'Rendszer' },
    upload: { label: 'Feltöltés', group: 'Rendszer' },
    tickets: { label: 'Hibajegyek', group: 'Rendszer' },
    integrations: { label: 'Integrációk', group: 'Rendszer' },
    settings: { label: 'Beállítások', group: 'Rendszer' },
    shipments: { label: 'Fuvarok', group: 'Szállítmányozás' },
    shipment_import: { label: 'Excel Import', group: 'Szállítmányozás' },
    shipment_matching: { label: 'Matching', group: 'Szállítmányozás' },
  },
  accounty: {
    portfolio: { label: 'Portfólió', group: 'Áttekintés' },
    missing_invoices: { label: 'Hiányzó számlák', group: 'Áttekintés' },
    tax_calendar: { label: 'Adó naptár', group: 'Áttekintés' },
    reports: { label: 'Riportok', group: 'Riportok' },
    approval_queue: { label: 'Jóváhagyó rendszer', group: 'Riportok' },
    alerts: { label: 'Riasztások', group: 'Riportok' },
    nav_deadlines: { label: 'NAV határidők', group: 'Riportok' },
    payroll: { label: 'Bérszámfejtés', group: 'Pénzügyek' },
    tao: { label: 'TAO / KIVA', group: 'Pénzügyek' },
    settings: { label: 'Beállítások', group: 'Pénzügyek' },
    admin_audit: { label: 'Audit napló', group: 'Rendszer' },
    admin_gdpr: { label: 'GDPR', group: 'Rendszer' },
    admin_templates: { label: 'Sablonok', group: 'Rendszer' },
    admin_job_codes: { label: 'Jogviszonykódok', group: 'Rendszer' },
    admin_tax_params: { label: 'Adómértékek', group: 'Rendszer' },
    admin_legal: { label: 'Jogszabály-frissítések', group: 'Rendszer' },
    admin_office: { label: 'Irodai beállítások', group: 'Rendszer' },
    admin_permissions: { label: 'Jogosultságkezelő', group: 'Rendszer' },
    admin_accountants: { label: 'Könyvelők kezelése', group: 'Rendszer' },
    onboarding: { label: 'Onboarding', group: 'Rendszer' },
    ai_assistant: { label: 'AI Asszisztens', group: 'AI & Segítség' },
    help: { label: 'Segítség', group: 'AI & Segítség' },
    profile: { label: 'Profil', group: 'AI & Segítség' },
    tickets: { label: 'Hibajegyek', group: 'AI & Segítség' },
  }
};
