import React from 'react';
import { describe, it, expect, vi } from 'vitest';
import { render, screen } from '@testing-library/react';
import { TicketTimeline } from '@/components/tickets/TicketTimeline';
import { useTicketEvents, type TicketEvent } from '@/hooks/useTickets';

vi.mock('@/hooks/useTickets', () => ({
  useTicketEvents: vi.fn(),
}));

describe('TicketTimeline Component', () => {
  it('suppresses redundant comment_added event paired with resolution_confirmed', () => {
    const confirmTime = new Date('2026-09-11T05:35:00.000Z').toISOString();
    const commentTime = new Date('2026-09-11T05:35:00.100Z').toISOString(); // 100ms later
    const normalCommentTime = new Date('2026-09-11T05:40:00.000Z').toISOString(); // 5 min later

    const mockEvents: TicketEvent[] = [
      {
        id: 'e-1',
        feedback_id: 'fb-1',
        event_type: 'created',
        actor_id: 'user-1',
        actor_email: 'user@test.com',
        actor_name: 'Teszt Elek',
        old_value: null,
        new_value: 'EB-0094',
        metadata: null,
        created_at: new Date('2026-09-10T10:00:00.000Z').toISOString(),
      },
      {
        id: 'e-2',
        feedback_id: 'fb-1',
        event_type: 'resolution_confirmed',
        actor_id: 'user-1',
        actor_email: 'user@test.com',
        actor_name: 'Teszt Elek',
        old_value: 'in_progress',
        new_value: 'resolved',
        metadata: { automatic_resolution: true },
        created_at: confirmTime,
      },
      {
        id: 'e-3',
        feedback_id: 'fb-1',
        event_type: 'comment_added',
        actor_id: 'user-1',
        actor_email: 'user@test.com',
        actor_name: 'Teszt Elek',
        old_value: null,
        new_value: null,
        metadata: { is_admin: false },
        created_at: commentTime, // Generated by auto confirmation comment
      },
      {
        id: 'e-4',
        feedback_id: 'fb-1',
        event_type: 'comment_added',
        actor_id: 'admin-1',
        actor_email: 'admin@test.com',
        actor_name: 'Admin Áron',
        old_value: null,
        new_value: null,
        metadata: { is_admin: true },
        created_at: normalCommentTime, // Independent normal comment
      },
    ];

    vi.mocked(useTicketEvents).mockReturnValue({
      data: mockEvents,
      isLoading: false,
    } as any);

    const { container } = render(<TicketTimeline feedbackId="fb-1" />);

    // Must display "megerősítette a megoldást"
    expect(screen.getByText('megerősítette a megoldást')).toBeInTheDocument();

    // Must display the independent normal comment from Admin Áron
    expect(screen.getByText('Admin Áron')).toBeInTheDocument();

    // Must NOT display "hozzászólást írt" for Teszt Elek
    // Because Teszt Elek's comment was the automated confirmation comment
    const commentAddedTexts = screen.getAllByText('hozzászólást írt');
    expect(commentAddedTexts).toHaveLength(1); // Only Admin Áron's comment

    // Verify connecting lines: for 3 rendered items (created, resolution_confirmed, admin comment),
    // there must be exactly 2 connecting line elements (n - 1)
    const connectorLines = container.querySelectorAll('.absolute.left-4.top-4.-bottom-2.w-px');
    expect(connectorLines).toHaveLength(2);
  });

  it('renders per-item connecting line on each item except the last', () => {
    const mockEvents: TicketEvent[] = [
      {
        id: 'e-1',
        feedback_id: 'fb-1',
        event_type: 'created',
        actor_id: 'user-1',
        actor_email: 'user@test.com',
        actor_name: 'Teszt Elek',
        old_value: null,
        new_value: 'EB-0094',
        metadata: null,
        created_at: new Date('2026-09-10T10:00:00.000Z').toISOString(),
      },
      {
        id: 'e-2',
        feedback_id: 'fb-1',
        event_type: 'status_changed',
        actor_id: 'admin-1',
        actor_email: 'admin@test.com',
        actor_name: 'Admin Áron',
        old_value: 'created',
        new_value: 'in_progress',
        metadata: null,
        created_at: new Date('2026-09-10T11:00:00.000Z').toISOString(),
      },
      {
        id: 'e-3',
        feedback_id: 'fb-1',
        event_type: 'resolution_requested',
        actor_id: 'admin-1',
        actor_email: 'admin@test.com',
        actor_name: 'Admin Áron',
        old_value: null,
        new_value: null,
        metadata: null,
        created_at: new Date('2026-09-10T12:00:00.000Z').toISOString(),
      },
      {
        id: 'e-4',
        feedback_id: 'fb-1',
        event_type: 'resolution_confirmed',
        actor_id: 'user-1',
        actor_email: 'user@test.com',
        actor_name: 'Teszt Elek',
        old_value: 'in_progress',
        new_value: 'resolved',
        metadata: null,
        created_at: new Date('2026-09-10T13:00:00.000Z').toISOString(),
      },
    ];

    vi.mocked(useTicketEvents).mockReturnValue({
      data: mockEvents,
      isLoading: false,
    } as any);

    const { container } = render(<TicketTimeline feedbackId="fb-1" />);

    // 4 items rendered, so exactly 3 connector lines
    const connectorLines = container.querySelectorAll('.absolute.left-4.top-4.-bottom-2.w-px');
    expect(connectorLines).toHaveLength(3);
  });
});
